### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'cafa3/test_df.pkl'

### ISSUE THREAD

**Issue by ZeroDesigner** [wzy-2020/MMSMAPlus#2]
Hi, when I run the code you offer.
The data and  the environment are ready. 

```
python generate_bert.py 
```

The error raise:

```
$ python generate_bert.py 
Traceback (most recent call last):
  File "/MMSMAPlus/seq_extract/generate_bert.py", line 123, in <module>
    main()
  File "/MMSMAPlus/seq_extract/generate_bert.py", line 37, in main
    seq_anno_df = pd.read_pickle(df_file)
  File "/miniconda/envs/sf/lib/python3.9/site-packages/pandas/io/pickle.py", line 179, in read_pickle
    with get_handle(
  File "/miniconda/envs/sf/lib/python3.9/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'cafa3/test_df.pkl'
```

Could you help me to solve it? Did I miss something?

**Comment by wzy-2020** [comment]
You can find the test_data.pkl file in data/cafa3 directory.

**Comment by ZeroDesigner** [comment]
> You can find the test_data.pkl file in data/cafa3 directory.

Yeah, I change 'test_df.pkl' to 'test_data.pkl'. It worked.

And when I to run ‘ python main.py --feats_type B_O_P_F’. The step 2. I meet this:

```
--- Current learning rate:  0.0005
[*] Epoch:1      Namespace:MF    net:MSMA        feat:B_O_P_F
  0%|                                                                                                                                                    | 0/2032 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/s0/ss/sf/Code/MMSMAPlus/main.py", line 191, in <module>
    main()
  File "/s0/ss/sf/Code/MMSMAPlus/main.py", line 96, in main
    train(opt=opt, net=net, criterion=criterion, train_loader=train_loader, valid_loader=valid_loader, test_loader=test_loader,ckpt_dir=ckpt_dir,
  File "/s0/ss/sf/Code/MMSMAPlus/model.py", line 43, in train
    for data in pbar:
  File "/home/ss/work/sf/software/conda/miniconda3/envs/sf/lib/python3.9/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/ss/work/sf/software/conda/miniconda3/envs/sf/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "sf/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "sf/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "sf/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/s0/ss/sf/Code/MMSMAPlus/datasets1.py", line 64, in __getitem__
    return features, seqlen,labels,sub_x1,sub_x2,sub_x3,sub_x4,sub_x5
UnboundLocalError: local variable 'features' referenced before assignment
```

Is there any other hyperparameter I need to add ?

**Comment by wzy-2020** [comment]
To run the model, you need to collect initial features constructed based on different theoretical foundations, B_O_P_W implies that it needs to be trained based on features such as bert, onehot, pssm as well as opf, etc., respectively, and you may need to modify the code accordingly if you use B_O_P_W as the name of the feature; otherwise, it can not  work.
